from __future__ import annotations

import json
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlsplit


ROOT = Path(__file__).resolve().parents[1]
CHINA = ROOT / "china"


class PageParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.hrefs: list[str] = []
        self.ids: list[str] = []
        self.canonicals: list[str] = []
        self.stylesheets: list[str] = []
        self.scripts: list[dict[str, str | None]] = []
        self._json_ld_depth = 0
        self._json_ld_parts: list[str] = []
        self.json_ld: list[dict] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        values = dict(attrs)
        if values.get("id"):
            self.ids.append(str(values["id"]))
        if tag == "a" and values.get("href"):
            self.hrefs.append(str(values["href"]))
        if tag == "link" and values.get("rel") == "canonical" and values.get("href"):
            self.canonicals.append(str(values["href"]))
        if tag == "link" and values.get("rel") == "stylesheet" and values.get("href"):
            self.stylesheets.append(str(values["href"]))
        if tag == "script":
            self.scripts.append(values)
            if values.get("type") == "application/ld+json":
                self._json_ld_depth += 1

    def handle_endtag(self, tag: str) -> None:
        if tag == "script" and self._json_ld_depth:
            self._json_ld_depth -= 1
            raw = "".join(self._json_ld_parts)
            self._json_ld_parts = []
            self.json_ld.append(json.loads(raw))

    def handle_data(self, data: str) -> None:
        if self._json_ld_depth:
            self._json_ld_parts.append(data)


def _html_pages() -> list[Path]:
    return sorted(CHINA.rglob("*.html"))


def _parser(path: Path) -> PageParser:
    parser = PageParser()
    parser.feed(path.read_text(encoding="utf-8"))
    return parser


def _route_to_path(href: str) -> Path:
    route = urlsplit(href).path
    assert route.startswith("/china/")
    relative = route.lstrip("/")
    if route.endswith("/"):
        relative += "index.html"
    return ROOT / relative


def test_exact_static_route_inventory_is_server_rendered():
    pages = _html_pages()
    assert len(pages) == 56
    assert len(list((CHINA / "sources").glob("*/index.html"))) == 33
    assert len(list((CHINA / "releases").glob("*/index.html"))) == 7
    assert len(list((CHINA / "domains").glob("*/index.html"))) == 12
    assert (CHINA / "index.html") in pages
    assert (CHINA / "sources" / "index.html") in pages
    assert (CHINA / "releases" / "index.html") in pages
    assert (CHINA / "domains" / "index.html") in pages


def test_every_page_has_compact_versioned_head_real_nav_and_unique_ids():
    for path in _html_pages():
        page = path.read_text(encoding="utf-8")
        parsed = _parser(path)
        assert page.startswith("<!doctype html>")
        assert '<meta name="palimpsest:schema-version" content="palimpsest-china-index.v1">' in page
        assert '<nav class="ps-nav" aria-label="Primary">' in page
        assert '<nav class="cn-local" aria-label="China Observatory">' in page
        assert '<main id="main" class="cn-main">' in page
        assert '<link rel="stylesheet" href="/assets/china.css">' in page
        assert '<script src="/assets/china.js" defer></script>' in page
        assert "<!-- GENERATED BY scripts/build_china_site.py -->" in page
        assert len(parsed.canonicals) == 1
        assert parsed.canonicals[0].startswith("https://palimpsest.info/china/")
        assert len(parsed.ids) == len(set(parsed.ids)), path
        assert len(parsed.json_ld) == 1
        assert parsed.json_ld[0]["url"] == parsed.canonicals[0]


def test_every_internal_china_link_resolves_to_an_ssr_page():
    broken: list[tuple[str, str]] = []
    for path in _html_pages():
        for href in _parser(path).hrefs:
            if not urlsplit(href).path.startswith("/china/"):
                continue
            target = _route_to_path(href)
            if not target.is_file():
                broken.append((str(path.relative_to(ROOT)), href))
    assert broken == []


def test_root_page_leads_with_abstention_and_retains_all_desks_and_releases():
    page = (CHINA / "index.html").read_text(encoding="utf-8")
    assert "The current read is <em>no broad direction.</em>" in page
    assert "4 of 4 gates" not in page
    assert page.count('class="cn-desk"') == 6
    assert page.count('/china/releases/cn-release-lag-') >= 7
    assert "Four rails, six desks, gaps left visible" in page
    assert page.count("cn-loom__cell--present") > 0
    assert page.count("cn-loom__cell--gap") > 0
    assert '<div class="cn-loom-wrap" role="region" tabindex="0"' in page
    assert '<table class="cn-loom">' in page
    assert page.count('<th class="cn-loom__label" scope="row">') == 4
    assert 'role="cell"' not in page
    assert "No metric is an estimate of true GDP." in page
    assert "Backtests published; forecasts withheld" in page
    assert "0 / 3" in page
    assert page.count('class="cn-forecast-target"') == 3
    assert page.count("No forecast is published.") == 3
    assert "/readings/china-econ-forecast-latest.json" in page


def test_source_details_expose_all_clocks_receipts_without_claiming_private_datasets():
    live = (CHINA / "sources" / "cfets_benchmarks" / "index.html").read_text(encoding="utf-8")
    blocked = (CHINA / "sources" / "cbb_private_panel" / "index.html").read_text(encoding="utf-8")

    for label in ("Period end", "Released", "Collected", "Revision", "Checksums"):
        assert label in live
    assert "observation " in live and "source bytes " in live
    assert '"@type":"WebPage"' in blocked
    assert '"@type":"Dataset"' not in blocked


def test_progressive_controls_are_revealed_only_after_successful_initialization():
    root = (CHINA / "index.html").read_text(encoding="utf-8")
    script = (ROOT / "assets" / "china.js").read_text(encoding="utf-8")
    assert 'document.documentElement.classList.add("cn-js")' not in root
    assert 'if (ready) document.documentElement.classList.add("cn-js")' in script


def test_progressive_filter_never_fetches_or_injects_markup():
    script = (ROOT / "assets" / "china.js").read_text(encoding="utf-8")
    assert "querySelectorAll(\"[data-cn-record]\")" in script
    assert "record.hidden = !show" in script
    assert "count.textContent" in script
    assert "fetch(" not in script
    assert ".innerHTML" not in script
    assert "document.write" not in script
    assert "eval(" not in script

    for name in ("sources", "releases", "domains"):
        page = (CHINA / name / "index.html").read_text(encoding="utf-8")
        assert "data-cn-controls" in page
        assert "data-cn-record" in page
        assert "data-cn-status" in page
        assert "data-cn-text" in page


def test_china_styles_use_the_evidence_palette_without_gradients_or_card_grid():
    css = (ROOT / "assets" / "china.css").read_text(encoding="utf-8").lower()
    for color in ("#eaf2f3", "#102a32", "#1f716f", "#b64235", "#a7782b", "#f9fcfc"):
        assert color in css
    assert "literata" in css
    assert "gradient(" not in css
    assert ".cn-loom" in css
    assert "prefers-reduced-motion" in css
    assert ":focus-visible" in css


def test_nested_sitemap_contains_every_html_canonical_once():
    sitemap = (CHINA / "sitemap.xml").read_text(encoding="utf-8")
    canonicals = [_parser(path).canonicals[0] for path in _html_pages()]
    assert sitemap.startswith('<?xml version="1.0" encoding="UTF-8"?>')
    assert sitemap.count("<url>") == len(canonicals) == 56
    for canonical in canonicals:
        assert sitemap.count(f"<loc>{canonical}</loc>") == 1
