#!/usr/bin/env python3
"""Build the static, evidence-bound China Observatory surface.

The build is deliberately offline.  It accepts four public evidence inputs
plus a presentation config, validates their joins, and writes a compact
machine index and server-rendered pages.  It never upgrades a registry status
because a related release happened to appear in the pulse.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import html
import json
import os
import re
import tempfile
from collections import Counter
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence
from urllib.parse import urlsplit

from core.econ_ledger import LedgerIntegrityError, LedgerSnapshot, load_snapshot
from core.econ_observation import EconomicObservation
from scripts import site_nav


ROOT = Path(__file__).resolve().parents[1]
SOURCE_REGISTRY = ROOT / "config" / "china_econ_sources.json"
SITE_CONFIG = ROOT / "config" / "china_site.json"
PULSE = ROOT / "readings" / "china-economic-pulse-latest.json"
LEDGER = ROOT / "readings" / "china-econ-observations.jsonl"
FORECAST = ROOT / "readings" / "china-econ-forecast-latest.json"
INDEX_OUTPUT = ROOT / "readings" / "china-index-latest.json"
SITE_ROOT = ROOT / "china"

INDEX_SCHEMA = "palimpsest-china-index.v1"
FORECAST_SCHEMA = "palimpsest-economic-forecast.v1"
MANIFEST_SCHEMA = "palimpsest-china-generated-manifest.v1"
GENERATED_MARKER = "<!-- GENERATED BY scripts/build_china_site.py -->"
MAX_JSON_BYTES = 12 * 1024 * 1024
MAX_LEDGER_BYTES = 32 * 1024 * 1024
MAX_LEDGER_ROWS = 100_000
MAX_LEDGER_LINE_BYTES = 256 * 1024
SLUG_RE = re.compile(r"^[a-z][a-z0-9_-]*$")
IMPLEMENTATIONS = {
    "live",
    "adapter_ready",
    "planned",
    "licensed_adapter",
    "blocked",
    "out_of_scope",
}
ALIAS_RELATIONSHIPS = {"exact_dataset", "publisher_family", "unregistered_release_surface"}


class ChinaSiteError(ValueError):
    """The publication inputs or managed output tree are unsafe or invalid."""


def _no_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    value: dict[str, Any] = {}
    for key, child in pairs:
        if key in value:
            raise ValueError(f"duplicate JSON key {key!r}")
        value[key] = child
    return value


def _reject_nonfinite(value: str) -> None:
    raise ValueError(f"non-finite JSON number {value}")


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def _read_bytes(path: Path, *, cap: int) -> bytes:
    try:
        size = path.stat().st_size
    except OSError as exc:
        raise ChinaSiteError(f"cannot inspect {_display_path(path)}: {exc}") from exc
    if size <= 0:
        raise ChinaSiteError(f"empty input: {_display_path(path)}")
    if size > cap:
        raise ChinaSiteError(
            f"input exceeds {cap} byte cap: {_display_path(path)} ({size} bytes)"
        )
    try:
        return path.read_bytes()
    except OSError as exc:
        raise ChinaSiteError(f"cannot read {_display_path(path)}: {exc}") from exc


def _read_json(path: Path) -> tuple[dict[str, Any], bytes]:
    raw = _read_bytes(path, cap=MAX_JSON_BYTES)
    try:
        value = json.loads(
            raw,
            object_pairs_hook=_no_duplicate_keys,
            parse_constant=_reject_nonfinite,
        )
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError, RecursionError) as exc:
        raise ChinaSiteError(f"invalid JSON in {_display_path(path)}: {exc}") from exc
    if not isinstance(value, dict):
        raise ChinaSiteError(f"expected JSON object in {_display_path(path)}")
    return value, raw


def _read_ledger(path: Path) -> tuple[list[EconomicObservation], LedgerSnapshot]:
    """Load the site's ledger through the repository's single trust boundary."""

    try:
        snapshot = load_snapshot(
            path,
            max_bytes=MAX_LEDGER_BYTES,
            max_rows=MAX_LEDGER_ROWS,
            max_record_bytes=MAX_LEDGER_LINE_BYTES,
        )
    except LedgerIntegrityError as exc:
        raise ChinaSiteError(f"invalid observation ledger: {exc}") from exc
    rows = list(snapshot.observations)
    if not rows:
        raise ChinaSiteError("observation ledger contains no records")
    return rows, snapshot


def _unique_by(values: Sequence[Mapping[str, Any]], key: str, label: str) -> dict[str, Mapping[str, Any]]:
    result: dict[str, Mapping[str, Any]] = {}
    for value in values:
        item_id = value.get(key)
        if not isinstance(item_id, str) or not SLUG_RE.fullmatch(item_id):
            raise ChinaSiteError(f"invalid {label} {key}: {item_id!r}")
        if item_id in result:
            raise ChinaSiteError(f"duplicate {label} {key}: {item_id}")
        result[item_id] = value
    return result


def _sha256(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _public_url(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ChinaSiteError(f"{label} must be a non-empty absolute HTTP(S) URL")
    try:
        parsed = urlsplit(value)
        hostname = parsed.hostname
    except ValueError as exc:
        raise ChinaSiteError(f"{label} must be an absolute HTTP(S) URL") from exc
    if parsed.scheme not in {"http", "https"} or not hostname:
        raise ChinaSiteError(f"{label} must be an absolute HTTP(S) URL")
    if parsed.username is not None or parsed.password is not None:
        raise ChinaSiteError(f"{label} must not contain URL credentials")
    return value


def _sorted_strings(values: Iterable[Any]) -> list[str]:
    return sorted({str(value) for value in values if value is not None})


def _validate_release_alias_inventory(
    *,
    alias_by_watch: Mapping[str, Mapping[str, Any]],
    release_by_watch: Mapping[str, Mapping[str, Any]],
    release_calendar: Mapping[str, Any],
) -> None:
    """Require an alias for every reporting or explicitly unreachable watch."""

    unreachable = release_calendar.get("unreachable")
    if not isinstance(unreachable, list):
        raise ChinaSiteError("release calendar unreachable inventory must be an array")
    unreachable_watch_ids: set[str] = set()
    for watch_id in unreachable:
        if not isinstance(watch_id, str) or not SLUG_RE.fullmatch(watch_id):
            raise ChinaSiteError(f"invalid unreachable release watch_id: {watch_id!r}")
        if watch_id in unreachable_watch_ids:
            raise ChinaSiteError(f"duplicate unreachable release watch_id: {watch_id}")
        unreachable_watch_ids.add(watch_id)

    reporting_watch_ids = set(release_by_watch)
    overlap = sorted(reporting_watch_ids & unreachable_watch_ids)
    if overlap:
        raise ChinaSiteError(
            f"release watches cannot be both reporting and unreachable: {overlap}"
        )
    reporting = release_calendar.get("reporting")
    if type(reporting) is not int or reporting != len(reporting_watch_ids):
        raise ChinaSiteError("release calendar reporting count is inconsistent")

    expected_watch_ids = reporting_watch_ids | unreachable_watch_ids
    watched = release_calendar.get("watched")
    if type(watched) is not int or watched != len(expected_watch_ids):
        raise ChinaSiteError("release calendar watched count is inconsistent")
    if set(alias_by_watch) != expected_watch_ids:
        missing = sorted(expected_watch_ids - set(alias_by_watch))
        extra = sorted(set(alias_by_watch) - expected_watch_ids)
        raise ChinaSiteError(
            "release aliases must cover reporting and explicitly unreachable watches; "
            f"missing={missing}, extra={extra}"
        )


def _latest_by_source_slice(
    rows: Sequence[EconomicObservation],
) -> list[dict[str, Any]]:
    """Select one latest period/vintage without collapsing independent slices."""

    selected: dict[tuple[str, ...], EconomicObservation] = {}
    for row in rows:
        source_slice = (*row.slice_key, row.source_id)
        key = (
            row.period_end,
            row.released_at,
            row.collected_at,
            row.revision,
            row.observation_id,
        )
        previous = selected.get(source_slice)
        if previous is None:
            selected[source_slice] = row
            continue
        previous_key = (
            previous.period_end,
            previous.released_at,
            previous.collected_at,
            previous.revision,
            previous.observation_id,
        )
        if key > previous_key:
            selected[source_slice] = row
    public_fields = (
        "observation_id",
        "series_id",
        "value",
        "unit",
        "frequency",
        "period_start",
        "period_end",
        "released_at",
        "collected_at",
        "source_id",
        "evidence_url",
        "revision",
        "status",
        "geography",
        "sector",
        "firm_size",
        "ownership",
        "quality",
        "raw_sha256",
    )
    result = []
    for source_slice in sorted(selected):
        encoded = selected[source_slice].to_dict()
        result.append({field: encoded[field] for field in public_fields})
    return result


def build_index(*, root: Path = ROOT) -> dict[str, Any]:
    """Build and validate the public normalized index without writing files."""

    registry, registry_raw = _read_json(root / "config" / "china_econ_sources.json")
    site_config, site_config_raw = _read_json(root / "config" / "china_site.json")
    pulse, pulse_raw = _read_json(root / "readings" / "china-economic-pulse-latest.json")
    rows, ledger_snapshot = _read_ledger(
        root / "readings" / "china-econ-observations.jsonl"
    )
    forecast, forecast_raw = _read_json(
        root / "readings" / "china-econ-forecast-latest.json"
    )

    if site_config.get("schema_version") != "palimpsest-china-site-config.v1":
        raise ChinaSiteError("unsupported china_site config schema")
    if pulse.get("schema_version") != "palimpsest-economic-pulse.v1":
        raise ChinaSiteError("unsupported China economic pulse schema")
    if forecast.get("schema_version") != FORECAST_SCHEMA:
        raise ChinaSiteError("unsupported China economic forecast schema")
    if not isinstance(registry.get("registry_version"), int):
        raise ChinaSiteError("source registry_version must be an integer")

    forecast_snapshot = forecast.get("snapshot")
    if not isinstance(forecast_snapshot, dict) or (
        forecast_snapshot.get("path") != "readings/china-econ-observations.jsonl"
        or forecast_snapshot.get("sha256") != ledger_snapshot.byte_sha256
        or forecast_snapshot.get("bytes") != ledger_snapshot.byte_size
        or forecast_snapshot.get("records") != ledger_snapshot.records
    ):
        raise ChinaSiteError("forecast snapshot does not match the exact observation ledger")
    forecast_registry = forecast.get("source_registry")
    if not isinstance(forecast_registry, dict) or (
        forecast_registry.get("sha256") != _sha256(registry_raw)
    ):
        raise ChinaSiteError("forecast source registry digest does not match")
    forecast_targets = forecast.get("targets")
    forecast_summary = forecast.get("summary")
    if (
        not isinstance(forecast_targets, list)
        or not forecast_targets
        or not isinstance(forecast_summary, dict)
        or forecast.get("n_targets") != len(forecast_targets)
        or forecast_summary.get("targets") != len(forecast_targets)
    ):
        raise ChinaSiteError("forecast target denominator is missing or inconsistent")
    compact_forecast_targets: list[dict[str, Any]] = []
    for target in forecast_targets:
        if not isinstance(target, dict) or target.get("status") not in {"warming_up", "ready"}:
            raise ChinaSiteError("forecast target has an invalid status")
        promotion = target.get("promotion")
        checks = promotion.get("checks") if isinstance(promotion, dict) else None
        if not isinstance(checks, list):
            raise ChinaSiteError(f"forecast target promotion checks missing: {target.get('target_id')}")
        if target["status"] == "warming_up" and (
            target.get("nowcast") is not None or promotion.get("champion_model_id") is not None
        ):
            raise ChinaSiteError("warming forecast target cannot publish a champion or nowcast")
        check_summary = {
            str(check.get("gate_id")): {
                "observed": copy.deepcopy(check.get("observed")),
                "required": copy.deepcopy(check.get("required")),
                "passed": check.get("passed") is True,
            }
            for check in checks
            if isinstance(check, dict) and isinstance(check.get("gate_id"), str)
        }
        compact_forecast_targets.append(
            {
                "target_id": str(target.get("target_id", "")),
                "label": str(target.get("label", "")),
                "series_id": str(target.get("series_id", "")),
                "status": target["status"],
                "outcome_periods": target.get("outcome_periods"),
                "observed_source_ids": copy.deepcopy(target.get("observed_source_ids", [])),
                "observed_independence_groups": copy.deepcopy(
                    target.get("observed_independence_groups", [])
                ),
                "champion_model_id": promotion.get("champion_model_id"),
                "nowcast": copy.deepcopy(target.get("nowcast")),
                "gate_checks": check_summary,
            }
        )

    source_values = registry.get("sources")
    desk_values = pulse.get("desks")
    release_calendar = pulse.get("release_calendar")
    if not isinstance(release_calendar, dict):
        raise ChinaSiteError("release calendar must be an object")
    release_values = release_calendar.get("entries")
    matrix_values = pulse.get("coverage", {}).get("matrix")
    aliases = site_config.get("release_source_aliases")
    if not all(isinstance(value, list) for value in (source_values, desk_values, release_values, matrix_values, aliases)):
        raise ChinaSiteError("registry, desk, release, matrix and alias collections must be arrays")

    source_by_id = _unique_by(source_values, "source_id", "source")
    for source in source_values:
        if source.get("implementation") not in IMPLEMENTATIONS:
            raise ChinaSiteError(f"invalid implementation for {source['source_id']}")
        for key in ("name", "publisher", "home_url", "evidence_url", "independence_group"):
            if not isinstance(source.get(key), str) or not source[key]:
                raise ChinaSiteError(f"source {source['source_id']} has invalid {key}")
        _public_url(source["home_url"], f"source {source['source_id']} home_url")
        _public_url(source["evidence_url"], f"source {source['source_id']} evidence_url")
        if not isinstance(source.get("domains"), list) or not isinstance(source.get("dimensions"), list):
            raise ChinaSiteError(f"source {source['source_id']} domains/dimensions must be arrays")

    _desk_by_id = _unique_by(desk_values, "id", "desk")
    release_by_watch = _unique_by(release_values, "watch_id", "release")
    matrix_by_domain = _unique_by(matrix_values, "domain", "domain")
    alias_by_watch = _unique_by(aliases, "watch_id", "release alias")
    _validate_release_alias_inventory(
        alias_by_watch=alias_by_watch,
        release_by_watch=release_by_watch,
        release_calendar=release_calendar,
    )

    domain_order = site_config.get("domain_order")
    labels = site_config.get("domain_labels")
    descriptions = site_config.get("domain_descriptions")
    if not isinstance(domain_order, list) or len(domain_order) != len(set(domain_order)):
        raise ChinaSiteError("domain_order must be a unique array")
    if set(domain_order) != set(matrix_by_domain):
        raise ChinaSiteError("domain_order must exactly cover the pulse coverage matrix")
    registered_domains = {domain for source in source_values for domain in source["domains"]}
    if registered_domains != set(domain_order):
        raise ChinaSiteError("source domains must exactly join to configured domains")
    if not isinstance(labels, dict) or set(labels) != set(domain_order):
        raise ChinaSiteError("domain_labels must exactly cover configured domains")
    if not isinstance(descriptions, dict) or set(descriptions) != set(domain_order):
        raise ChinaSiteError("domain_descriptions must exactly cover configured domains")

    release_metric_ids: set[str] = set()
    releases: list[dict[str, Any]] = []
    release_source_to_registry: dict[str, str] = {}
    for entry in release_values:
        metric_id = entry.get("metric_id")
        if not isinstance(metric_id, str) or not SLUG_RE.fullmatch(metric_id):
            raise ChinaSiteError(f"invalid release metric_id: {metric_id!r}")
        if metric_id in release_metric_ids:
            raise ChinaSiteError(f"duplicate release metric_id: {metric_id}")
        release_metric_ids.add(metric_id)
        alias = alias_by_watch[entry["watch_id"]]
        if alias.get("release_source_id") != entry.get("source_id"):
            raise ChinaSiteError(f"release alias source mismatch: {entry['watch_id']}")
        registry_source_id = alias.get("registry_source_id")
        relationship = alias.get("relationship")
        if relationship not in ALIAS_RELATIONSHIPS:
            raise ChinaSiteError(f"release alias relationship invalid: {entry['watch_id']}")
        if relationship == "unregistered_release_surface":
            if registry_source_id is not None:
                raise ChinaSiteError(
                    f"unregistered release alias must have a null target: {entry['watch_id']}"
                )
        elif registry_source_id not in source_by_id:
            raise ChinaSiteError(f"release alias target missing: {registry_source_id}")
        if not isinstance(alias.get("note"), str) or not alias["note"].strip():
            raise ChinaSiteError(f"release alias note missing: {entry['watch_id']}")
        if registry_source_id is not None:
            release_source_to_registry[str(entry["source_id"])] = str(registry_source_id)
        release = copy.deepcopy(entry)
        evidence = release.get("evidence")
        if not isinstance(evidence, dict):
            raise ChinaSiteError(f"release evidence missing: {entry['watch_id']}")
        _public_url(evidence.get("url"), f"release {entry['watch_id']} evidence.url")
        release["registry_source_id"] = registry_source_id
        release["registry_relationship"] = alias["relationship"]
        release["registry_relationship_note"] = alias["note"]
        releases.append(release)
    releases.sort(key=lambda value: value["metric_id"])

    all_metrics: list[dict[str, Any]] = []
    metric_ids: set[str] = set()
    metrics_by_registry_source: dict[str, list[str]] = {source_id: [] for source_id in source_by_id}
    for desk in desk_values:
        metrics = desk.get("metrics")
        if not isinstance(metrics, list) or desk.get("n_metrics") != len(metrics):
            raise ChinaSiteError(f"desk metric count mismatch: {desk['id']}")
        for raw_metric in metrics:
            metric_id = raw_metric.get("metric_id")
            if not isinstance(metric_id, str) or metric_id in metric_ids:
                raise ChinaSiteError(f"invalid or duplicate pulse metric_id: {metric_id!r}")
            metric_ids.add(metric_id)
            metric = copy.deepcopy(raw_metric)
            metric["desk_id"] = desk["id"]
            source_id = str(metric.get("source_id", ""))
            registry_ids: list[str] = []
            if source_id in source_by_id:
                registry_ids.append(source_id)
            elif source_id in release_source_to_registry:
                registry_ids.append(release_source_to_registry[source_id])
            metric["registry_source_ids"] = registry_ids
            for registry_id in registry_ids:
                metrics_by_registry_source[registry_id].append(metric_id)
            all_metrics.append(metric)

    ledger_source_ids = {row.source_id for row in rows}
    unknown_ledger_sources = sorted(ledger_source_ids - set(source_by_id))
    if unknown_ledger_sources:
        raise ChinaSiteError(f"ledger source ids missing from registry: {unknown_ledger_sources}")

    observation_counts = Counter(row.source_id for row in rows)
    releases_by_registry_source: dict[str, list[str]] = {source_id: [] for source_id in source_by_id}
    for release in releases:
        if release["registry_source_id"] is not None:
            releases_by_registry_source[release["registry_source_id"]].append(release["metric_id"])
    sources: list[dict[str, Any]] = []
    for raw_source in source_values:
        source = copy.deepcopy(raw_source)
        source_id = source["source_id"]
        source["pulse_metric_ids"] = sorted(metrics_by_registry_source[source_id])
        source["release_monitor_ids"] = sorted(releases_by_registry_source[source_id])
        source["observation_count"] = observation_counts[source_id]
        sources.append(source)
    sources.sort(key=lambda value: value["source_id"])

    domains: list[dict[str, Any]] = []
    for domain_id in domain_order:
        matrix = copy.deepcopy(matrix_by_domain[domain_id])
        matrix["label"] = labels[domain_id]
        matrix["description"] = descriptions[domain_id]
        matrix["source_ids"] = sorted(
            source["source_id"] for source in sources if domain_id in source["domains"]
        )
        domain_metric_ids: set[str] = set()
        for source_id in matrix["source_ids"]:
            domain_metric_ids.update(metrics_by_registry_source[source_id])
        matrix["pulse_metric_ids"] = sorted(domain_metric_ids)
        domains.append(matrix)

    rail_config = site_config.get("evidence_rails")
    if not isinstance(rail_config, list) or len(rail_config) != 4:
        raise ChinaSiteError("evidence_rails must contain four rails")
    evidence_rails: list[dict[str, Any]] = []
    for rail in rail_config:
        rail_id = rail.get("rail_id")
        if rail_id not in {"official", "market", "physical", "integrity"}:
            raise ChinaSiteError(f"invalid evidence rail: {rail_id}")
        desk_cells: list[bool] = []
        observed_metrics = 0
        for desk in desk_values:
            metrics = desk["metrics"]
            if "metric_source_class" in rail:
                matches = [
                    metric for metric in metrics
                    if metric.get("source_class") == rail["metric_source_class"]
                ]
            else:
                matches = list(metrics) if desk["id"] == rail.get("desk_id") else []
            desk_cells.append(bool(matches))
            observed_metrics += len(matches)
        evidence_rails.append(
            {
                "rail_id": rail_id,
                "label": str(rail.get("label", rail_id)),
                "observed_metrics": observed_metrics,
                "desk_cells": desk_cells,
            }
        )

    implementations = Counter(str(source["implementation"]) for source in sources)
    series_ids = _sorted_strings(row.series_id for row in rows)
    ledger_summary = {
        "artifact": {
            "path": "readings/china-econ-observations.jsonl",
            "media_type": "application/x-ndjson",
            "bytes": ledger_snapshot.byte_size,
            "sha256": ledger_snapshot.byte_sha256,
        },
        "record_count": len(rows),
        "unique_observation_count": len({row.observation_id for row in rows}),
        "source_ids": sorted(ledger_source_ids),
        "series_ids": series_ids,
        "release_clock": {
            "first": min(row.released_at for row in rows).isoformat(),
            "last": max(row.released_at for row in rows).isoformat(),
        },
        "collection_clock": {
            "first": min(row.collected_at for row in rows).isoformat(),
            "last": max(row.collected_at for row in rows).isoformat(),
        },
        "period_coverage": {
            "first": min(row.period_start for row in rows).isoformat(),
            "last": max(row.period_end for row in rows).isoformat(),
        },
        "dimensions": {
            "geography": _sorted_strings(row.geography for row in rows),
            "sector": _sorted_strings(row.sector for row in rows),
            "firm_size": _sorted_strings(row.firm_size for row in rows),
            "ownership": _sorted_strings(row.ownership for row in rows),
        },
        "latest_by_source_slice": _latest_by_source_slice(rows),
    }

    limitations = list(pulse.get("economic_state", {}).get("prohibited_interpretations", []))
    limitations.extend(
        [
            str(pulse.get("readiness", {}).get("abstention_reason", "")),
            str(registry.get("replicability_note", "")),
            str(registry.get("safety_rule", "")),
            str(pulse.get("release_calendar", {}).get("limitation", "")),
        ]
    )
    limitations = [value for value in dict.fromkeys(limitations) if value]

    return {
        "schema_version": INDEX_SCHEMA,
        "generated_at": pulse["generated_at"],
        "source": pulse["source"],
        "method": pulse["method"],
        "scope": pulse["scope"],
        "n_sources": len(sources),
        "head": {
            "index_id": "palimpsest-china-observatory",
            "as_of": pulse["as_of"],
            "generated_at": pulse["generated_at"],
            "pulse_schema_version": pulse["schema_version"],
            "source_registry_version": registry["registry_version"],
            "input_sha256": {
                "source_registry": _sha256(registry_raw),
                "presentation_config": _sha256(site_config_raw),
                "economic_pulse": _sha256(pulse_raw),
                "observation_ledger": ledger_snapshot.byte_sha256,
                "economic_forecast": _sha256(forecast_raw),
            },
        },
        "counts": {
            "sources": len(sources),
            "source_implementations": dict(sorted(implementations.items())),
            "domains": len(domains),
            "desks": len(desk_values),
            "metrics": len(all_metrics),
            "release_monitors": len(releases),
            "observations": len(rows),
            "series": len(series_ids),
            "forecast_targets": len(compact_forecast_targets),
            "forecast_ready_targets": int(forecast_summary.get("ready_targets", 0)),
        },
        "economic_state": copy.deepcopy(pulse["economic_state"]),
        "readiness": copy.deepcopy(pulse["readiness"]),
        "evidence_rails": evidence_rails,
        "desks": copy.deepcopy(desk_values),
        "domains": domains,
        "releases": releases,
        "sources": sources,
        "observation_ledger": ledger_summary,
        "forecast": {
            "artifact": {
                "path": "readings/china-econ-forecast-latest.json",
                "schema": "protocol/economic-forecast-v1.schema.json",
                "bytes": len(forecast_raw),
                "sha256": _sha256(forecast_raw),
            },
            "generated_at": forecast.get("generated_at"),
            "as_of": forecast.get("as_of"),
            "status": forecast.get("status"),
            "scope": forecast.get("scope"),
            "claim": forecast.get("claim"),
            "summary": copy.deepcopy(forecast_summary),
            "targets": compact_forecast_targets,
            "limitations": copy.deepcopy(forecast.get("limitations", [])),
        },
        "input_integrity": copy.deepcopy(pulse.get("input_integrity", [])),
        "limitations": limitations,
    }


def canonical_json(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8")


def _e(value: Any) -> str:
    return html.escape(str(value), quote=True)


def _status_label(value: str) -> str:
    return value.replace("_", " ")


def _status_badge(value: str) -> str:
    safe = re.sub(r"[^a-z0-9-]", "-", value.lower().replace("_", "-"))
    return f'<span class="cn-status cn-status--{safe}">{_e(_status_label(value))}</span>'


def _fmt_value(value: Any) -> str:
    if value is None:
        return "not available"
    if isinstance(value, float):
        return f"{value:,.6f}".rstrip("0").rstrip(".")
    return str(value)


def _local_nav(route: str) -> str:
    links = (
        ("/china/", "Current read"),
        ("/china/sources/", "Source ledger"),
        ("/china/releases/", "Release docket"),
        ("/china/domains/", "Coverage domains"),
        ("/readings/china-index-latest.json", "Machine index"),
    )
    parts = ['<nav class="cn-local" aria-label="China Observatory">']
    for href, label in links:
        current = ""
        if route == href:
            current = ' aria-current="page"'
        elif href != "/china/" and route.startswith(href):
            current = ' aria-current="location"'
        parts.append(f'<a href="{href}"{current}>{label}</a>')
    parts.append("</nav>")
    return "".join(parts)


def _breadcrumbs(items: Sequence[tuple[str, str]]) -> str:
    parts = ['<nav class="cn-crumbs" aria-label="Breadcrumb"><ol>']
    for index, (label, href) in enumerate(items):
        if index == len(items) - 1:
            parts.append(f'<li aria-current="page">{_e(label)}</li>')
        else:
            parts.append(f'<li><a href="{_e(href)}">{_e(label)}</a></li>')
    parts.append("</ol></nav>")
    return "".join(parts)


def _page(
    *,
    title: str,
    description: str,
    route: str,
    body: str,
    index: Mapping[str, Any],
    page_type: str = "CollectionPage",
) -> bytes:
    canonical = f"https://palimpsest.info{route}"
    structured = {
        "@context": "https://schema.org",
        "@type": page_type,
        "name": title,
        "description": description,
        "url": canonical,
        "dateModified": index["head"]["generated_at"],
        "isPartOf": {
            "@type": "WebSite",
            "name": "Palimpsest Observatory",
            "url": "https://palimpsest.info/",
        },
    }
    json_ld = json.dumps(structured, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    document = f'''<!doctype html>
<html lang="en" data-tk-theme="light" data-cn-schema-version="{INDEX_SCHEMA}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{_e(title)} · Palimpsest</title>
<meta name="description" content="{_e(description)}">
<meta name="robots" content="index,follow,max-snippet:-1">
<meta name="palimpsest:schema-version" content="{INDEX_SCHEMA}">
<link rel="canonical" href="{_e(canonical)}">
<link rel="icon" type="image/svg+xml" href="/brand/palimpsest-icon.svg">
<meta name="theme-color" content="#eaf2f3">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Palimpsest Observatory">
<meta property="og:title" content="{_e(title)}">
<meta property="og:description" content="{_e(description)}">
<meta property="og:url" content="{_e(canonical)}">
<script type="application/ld+json">{json_ld}</script>
{site_nav.HEAD}
<link rel="stylesheet" href="/assets/china.css">
</head>
<body class="ps tk cn-page">
{GENERATED_MARKER}
{site_nav.render(route)}
{_local_nav(route)}
<main id="main" class="cn-main">
{body}
</main>
<footer class="cn-footer">
  <p><strong>Palimpsest China Observatory</strong> · Aggregate evidence, explicit clocks, visible abstention.</p>
  <p><a href="/readings/china-index-latest.json">JSON index</a> · <a href="/readings/china-econ-observations.jsonl">Bitemporal ledger</a> · <a href="/protocol/china-index-v1.schema.json">Schema</a></p>
</footer>
{site_nav.FOOT}
<script src="/assets/china.js" defer></script>
</body>
</html>
'''
    return document.encode("utf-8")


def _controls(*, statuses: Sequence[str], noun: str) -> str:
    options = ['<option value="all">All states</option>']
    options.extend(
        f'<option value="{_e(status)}">{_e(_status_label(status))}</option>'
        for status in statuses
    )
    return (
        '<div class="cn-controls" data-cn-controls>'
        f'<label>Find {noun}<input type="search" data-cn-search autocomplete="off" '
        f'placeholder="Search {noun}, publisher or domain"></label>'
        '<label>Evidence state<select data-cn-filter>' + "".join(options) + "</select></label>"
        '<p class="cn-result-count" data-cn-result-count aria-live="polite"></p>'
        '</div>'
    )


def _loom(index: Mapping[str, Any]) -> str:
    desks = index["desks"]
    parts = [
        '<section class="cn-section cn-section--loom" aria-labelledby="loom-title">',
        '<div class="cn-section__head"><p class="cn-kicker">Evidence loom</p>',
        '<h2 id="loom-title">Four rails, six desks, gaps left visible</h2>',
        '<p>Each filled crossing means the desk contains at least one retained metric on that evidence rail. An open crossing means no such metric is currently published.</p></div>',
        '<p class="cn-table-cue" id="loom-scroll-cue">Scroll horizontally to inspect every desk.</p>',
        '<div class="cn-loom-wrap" role="region" tabindex="0" '
        'aria-label="Evidence rails by economic desk; horizontally scrollable" '
        'aria-describedby="loom-scroll-cue">',
        '<table class="cn-loom">',
        '<caption class="cn-visually-hidden">Published metric coverage for four evidence rails across six economic desks</caption>',
        '<thead><tr><th class="cn-loom__corner" scope="col">rail / desk</th>',
    ]
    for desk in desks:
        parts.append(f'<th class="cn-loom__desk" scope="col">{_e(desk["title"])}</th>')
    parts.append("</tr></thead><tbody>")
    for rail in index["evidence_rails"]:
        parts.append(
            '<tr>'
            f'<th class="cn-loom__label" scope="row"><b>{_e(rail["label"])}</b>'
            f'<span>{rail["observed_metrics"]} metrics</span></th>'
        )
        for desk, active in zip(desks, rail["desk_cells"]):
            state = "present" if active else "gap"
            label = f'{rail["label"]} / {desk["title"]}: {state}'
            parts.append(
                f'<td class="cn-loom__cell cn-loom__cell--{state}" title="{_e(label)}">'
                f'<span aria-hidden="true"></span><span class="cn-visually-hidden">{_e(state)}</span></td>'
            )
        parts.append("</tr>")
    parts.append("</tbody></table></div></section>")
    return "".join(parts)


def _home(index: Mapping[str, Any]) -> bytes:
    state = index["economic_state"]
    readiness = index["readiness"]
    forecast = index["forecast"]
    direction = state.get("direction")
    current_read = (
        str(direction).replace("_", " ")
        if state.get("status") == "ready" and direction
        else "no broad direction"
    )
    failed = len(readiness.get("failed_gate_ids", []))
    gate_items = []
    for gate in readiness["gates"]:
        result = "pass" if gate["passed"] else "not met"
        gate_items.append(
            f'<li class="cn-gate cn-gate--{"pass" if gate["passed"] else "fail"}">'
            f'<span>{_e(gate["label"])}</span><b>{_e(gate["observed"])} / {_e(gate["minimum"])}</b>'
            f'<small>{result}</small></li>'
        )

    forecast_rows = []
    for target in forecast["targets"]:
        checks = target["gate_checks"]
        failed_target_gates = sum(not check["passed"] for check in checks.values())
        history_days = checks.get("history-span-days", {}).get("observed", "not available")
        first_folds = checks.get("first-release-folds", {}).get("observed", "not available")
        revisions = checks.get("revised-outcomes", {}).get("observed", "not available")
        champion = target["champion_model_id"] or "withheld"
        forecast_rows.append(
            '<li class="cn-forecast-target">'
            f'<header><div><p class="cn-kicker">{_e(target["series_id"])}</p>'
            f'<h3>{_e(target["label"])}</h3></div>{_status_badge(target["status"])}</header>'
            '<dl>'
            f'<div><dt>History</dt><dd>{_e(history_days)} days</dd></div>'
            f'<div><dt>Usable first-release folds</dt><dd>{_e(first_folds)}</dd></div>'
            f'<div><dt>Revised outcomes</dt><dd>{_e(revisions)}</dd></div>'
            f'<div><dt>Source families</dt><dd>{len(target["observed_source_ids"])}</dd></div>'
            f'<div><dt>Independent groups</dt><dd>{len(target["observed_independence_groups"])}</dd></div>'
            f'<div><dt>Champion</dt><dd>{_e(champion)}</dd></div>'
            '</dl>'
            f'<p>{failed_target_gates} of {len(checks)} promotion gates not met. '
            f'{"No forecast is published." if target["nowcast"] is None else "A gated forecast is available in the artifact."}</p>'
            '</li>'
        )

    desk_rows = []
    for desk in index["desks"]:
        metric_rows = []
        for metric in desk["metrics"]:
            metric_rows.append(
                '<tr>'
                f'<th scope="row">{_e(metric["label"])}</th>'
                f'<td class="cn-num">{_e(_fmt_value(metric.get("value")))} {_e(metric.get("unit", ""))}</td>'
                f'<td>{_status_badge(str(metric.get("status", "unknown")))}</td>'
                f'<td class="cn-mono">{_e(metric.get("period_end") or metric.get("latest_period") or "—")}</td>'
                '</tr>'
            )
        details = (
            '<details><summary>Inspect retained metrics</summary>'
            '<div class="cn-table-wrap"><table><thead><tr><th>Metric</th><th>Value</th><th>State</th><th>Period end</th></tr></thead>'
            f'<tbody>{"".join(metric_rows)}</tbody></table></div></details>'
            if metric_rows
            else '<p class="cn-empty">No retained metrics. This is a coverage gap, not a zero.</p>'
        )
        desk_rows.append(
            f'<article class="cn-desk"><header><p class="cn-kicker">{_e(desk["id"])}</p>'
            f'<h3>{_e(desk["title"])}</h3>{_status_badge(desk["status"])}'
            f'<span class="cn-desk__count">{desk["n_metrics"]} metrics</span></header>{details}</article>'
        )

    release_rows = []
    for release in index["releases"]:
        freshness = release.get("freshness", {})
        release_rows.append(
            '<tr>'
            f'<th scope="row"><a href="/china/releases/{_e(release["metric_id"])}/">{_e(release["label"])}</a></th>'
            f'<td>{_e(release.get("latest_publication_date") or "not available")}</td>'
            f'<td class="cn-num">{_e(_fmt_value(release.get("value")))} {_e(release.get("unit", ""))}</td>'
            f'<td>{_status_badge(str(freshness.get("status", release.get("status", "unknown"))))}</td>'
            '</tr>'
        )

    domain_rows = []
    for domain in index["domains"]:
        domain_rows.append(
            '<li>'
            f'<a href="/china/domains/{_e(domain["domain"])}/"><b>{_e(domain["label"])}</b>'
            f'<span>{_e(domain["description"])}</span></a>'
            f'{_status_badge(domain["status"])}'
            '</li>'
        )

    body = f'''
{_breadcrumbs((("China Observatory", "/china/"),))}
<header class="cn-hero">
  <div class="cn-hero__copy">
    <p class="cn-kicker">China / economic observatory / as of {_e(index["head"]["as_of"])}</p>
    <h1>The current read is <em>{_e(current_read)}.</em></h1>
    <p class="cn-hero__claim">{_e(state["claim"])}</p>
  </div>
  <aside class="cn-abstain" aria-label="Model readiness">
    <p>Publication state</p>
    <strong>{_e(_status_label(state["status"]))}</strong>
    <span>{failed} of {len(readiness["gates"])} gates not met</span>
  </aside>
</header>
<section class="cn-trust" aria-label="Publication provenance">
  <span><b>{index["counts"]["metrics"]}</b> pulse metrics</span>
  <span><b>{index["counts"]["observations"]}</b> ledger observations</span>
  <span><b>{index["counts"]["sources"]}</b> registered source families</span>
  <span><b>{index["counts"]["release_monitors"]}</b> release monitors</span>
  <a href="/readings/china-index-latest.json">inspect index</a>
</section>
<section class="cn-section cn-readiness" aria-labelledby="readiness-title">
  <div class="cn-section__head"><p class="cn-kicker">Abstention gate</p><h2 id="readiness-title">What prevents a composite</h2>
  <p>{_e(readiness["abstention_reason"])}</p></div>
  <ul class="cn-gates">{"".join(gate_items)}</ul>
</section>
<section class="cn-section cn-forecast" aria-labelledby="forecast-title">
  <div class="cn-section__head"><p class="cn-kicker">Pseudo-real-time forecast audit</p><h2 id="forecast-title">Backtests published; forecasts withheld</h2>
  <p>{_e(forecast["claim"])}</p></div>
  <div class="cn-forecast__summary"><strong>{forecast["summary"]["ready_targets"]} / {forecast["summary"]["targets"]}</strong><span>targets pass every frozen promotion gate</span>{_status_badge(forecast["status"])}</div>
  <ol class="cn-forecast-ledger">{"".join(forecast_rows)}</ol>
  <p class="cn-more"><a href="/readings/china-econ-forecast-latest.json">Inspect every fold, miss and failed model →</a> · <a href="/protocol/economic-forecast-v1.schema.json">schema</a></p>
</section>
{_loom(index)}
<section class="cn-section" aria-labelledby="desks-title">
  <div class="cn-section__head"><p class="cn-kicker">{index["counts"]["desks"]} desks</p><h2 id="desks-title">Observed evidence before interpretation</h2>
  <p>Values remain attached to source class, period and status. Open a desk to inspect every retained metric.</p></div>
  <div class="cn-desks">{"".join(desk_rows)}</div>
</section>
<section class="cn-section" aria-labelledby="releases-title">
  <div class="cn-section__head"><p class="cn-kicker">Release docket</p><h2 id="releases-title">{index["counts"]["release_monitors"]} publication clocks</h2>
  <p>Age measures publication visibility. It is not a surprise index and not evidence of economic direction.</p></div>
  <div class="cn-table-wrap"><table><thead><tr><th>Watch</th><th>Latest publication</th><th>Age</th><th>Freshness</th></tr></thead>
  <tbody>{"".join(release_rows)}</tbody></table></div>
  <p class="cn-more"><a href="/china/releases/">Open the full release docket →</a></p>
</section>
<section class="cn-section" aria-labelledby="domains-title">
  <div class="cn-section__head"><p class="cn-kicker">Coverage ledger</p><h2 id="domains-title">{index["counts"]["domains"]} economic domains</h2>
  <p>“Adapter ready” means a lawful source route has been designed. It never means the source is currently collected.</p></div>
  <ul class="cn-domain-grid">{"".join(domain_rows)}</ul>
  <p class="cn-more"><a href="/china/sources/">Audit all {index["counts"]["sources"]} source families →</a></p>
</section>
<section class="cn-section" aria-labelledby="access-title">
  <div class="cn-section__head"><p class="cn-kicker">Access boundary</p><h2 id="access-title">Acquire the evidence without inventing independence</h2>
  <p>Distribution, original measurement and a proprietary panel are different things. Palimpsest records the relationship instead of counting every transport as a new source.</p></div>
  <p class="cn-table-cue" id="access-scroll">Scroll horizontally to compare access and reuse boundaries.</p>
  <div class="cn-table-wrap" role="region" tabindex="0" aria-label="China data product access comparison; horizontally scrollable" aria-describedby="access-scroll">
    <table><caption class="cn-visually-hidden">Legitimate access, information independence and reuse boundaries for ChinaData.Live, China Beige Book and Palimpsest</caption>
      <thead><tr><th scope="col">Product</th><th scope="col">Legitimate access</th><th scope="col">Independent information?</th><th scope="col">Boundary</th></tr></thead>
      <tbody>
        <tr><th scope="row"><a href="https://chinadata.live/api/docs/" rel="noopener">ChinaData.Live API ↗</a></th><td>Public catalogue and per-dataset JSON/CSV under its terms; recurring or bulk delivery by agreement.</td><td>No, when it transports the same official release.</td><td><a href="https://chinadata.live/terms/" rel="noopener">Respect rate, source-rights and bulk-use terms ↗</a></td></tr>
        <tr><th scope="row"><a href="https://www.chinabeigebook.com/analytics-platform/" rel="noopener">China Beige Book ↗</a></th><td>Direct commercial licence with negotiated delivery and derived-output rights.</td><td>Yes: its value is a proprietary firm network.</td><td>No respondent data or CBB-branded substitute without a licence; see the <a href="/china/sources/cbb_private_panel/">source record</a>.</td></tr>
        <tr><th scope="row">Palimpsest</th><td>Public static files, schemas, OpenAPI and read-only MCP.</td><td>Only where a distinct source family is actually observed.</td><td>The current ledger is narrow; gaps and withheld forecasts remain visible.</td></tr>
      </tbody>
    </table>
  </div>
</section>
<aside class="cn-limit" aria-labelledby="limits-title"><p class="cn-kicker">Interpretation boundary</p><h2 id="limits-title">What this surface refuses to claim</h2>
<ul>{''.join(f'<li>{_e(value)}</li>' for value in index['limitations'][:5])}</ul></aside>
'''
    return _page(
        title="China economic observatory",
        description="A source-bound view of China economic evidence, release clocks, coverage gaps and bitemporal observations.",
        route="/china/",
        body=body,
        index=index,
        page_type="Dataset",
    )


def _sources_index(index: Mapping[str, Any]) -> bytes:
    rows = []
    statuses = sorted(index["counts"]["source_implementations"])
    for source in index["sources"]:
        search = " ".join(
            [source["name"], source["publisher"], source["source_id"], *source["domains"]]
        )
        rows.append(
            f'<li class="cn-record" data-cn-record data-cn-status="{_e(source["implementation"])}" data-cn-text="{_e(search.lower())}">'
            f'<a class="cn-record__main" href="/china/sources/{_e(source["source_id"])}/">'
            f'<span class="cn-record__id">{_e(source["source_id"])}</span><b>{_e(source["name"])}</b>'
            f'<span>{_e(source["publisher"])}</span></a>'
            f'<div class="cn-record__state">{_status_badge(source["implementation"])}<span>{_e(source["cadence"])}</span></div>'
            f'<p>{_e(", ".join(source["domains"]))}</p></li>'
        )
    body = f'''
{_breadcrumbs((("China Observatory", "/china/"), ("Source ledger", "/china/sources/")))}
<header class="cn-pagehead"><p class="cn-kicker">Source ledger / {index["counts"]["sources"]} families</p><h1>Every route, including the ones we cannot collect</h1>
<p>Implementation state comes directly from the registry. Related pulse evidence never promotes a planned, licensed, blocked or out-of-scope source.</p></header>
{_controls(statuses=statuses, noun="sources")}
<ul class="cn-records" data-cn-list>{''.join(rows)}</ul>
<aside class="cn-limit"><h2>Registry boundary</h2><p>{_e(index['limitations'][-3])}</p><p>{_e(index['limitations'][-2])}</p></aside>
'''
    return _page(
        title="China source ledger",
        description="All public, planned, licensed, blocked and out-of-scope China economic source families tracked by Palimpsest.",
        route="/china/sources/",
        body=body,
        index=index,
    )


def _source_detail(source: Mapping[str, Any], index: Mapping[str, Any]) -> bytes:
    metric_by_id = {
        metric["metric_id"]: metric
        for desk in index["desks"]
        for metric in desk["metrics"]
    }
    release_by_id = {release["metric_id"]: release for release in index["releases"]}
    latest = [
        row for row in index["observation_ledger"]["latest_by_source_slice"]
        if row["source_id"] == source["source_id"]
    ]
    metrics = [metric_by_id[value] for value in source["pulse_metric_ids"]]
    releases = [release_by_id[value] for value in source["release_monitor_ids"]]

    metric_rows = "".join(
        '<tr>'
        f'<th scope="row">{_e(metric["label"])}</th>'
        f'<td class="cn-num">{_e(_fmt_value(metric.get("value")))} {_e(metric.get("unit", ""))}</td>'
        f'<td>{_status_badge(str(metric.get("status", "unknown")))}</td>'
        '</tr>'
        for metric in metrics
    )
    release_items = "".join(
        f'<li><a href="/china/releases/{_e(release["metric_id"])}/">{_e(release["label"])}</a>'
        f'<span>{_e(_status_label(release["registry_relationship"]))}</span></li>'
        for release in releases
    )
    observation_rows = "".join(
        '<tr>'
        f'<th scope="row">{_e(row["series_id"])}<small>{_e(row["geography"])} · {_e(row["sector"])} · {_e(row["firm_size"])} · {_e(row["ownership"])}</small></th>'
        f'<td class="cn-num">{_e(_fmt_value(row["value"]))} {_e(row["unit"])}</td>'
        f'<td><time datetime="{_e(row["period_end"])}">{_e(row["period_end"])}</time></td>'
        f'<td><time datetime="{_e(row["released_at"])}">{_e(row["released_at"])}</time></td>'
        f'<td><time datetime="{_e(row["collected_at"])}">{_e(row["collected_at"])}</time></td>'
        f'<td class="cn-num">{_e(row["revision"])}</td>'
        f'<td><a href="{_e(row["evidence_url"])}" rel="noopener">Evidence ↗</a>'
        '<details><summary>Checksums</summary>'
        f'<span>observation {_e(row["observation_id"])}</span>'
        f'<span>source bytes {_e(row["raw_sha256"] or "not retained")}</span>'
        '</details></td>'
        '</tr>'
        for row in latest
    )
    domain_links = "".join(
        f'<a class="cn-chip" href="/china/domains/{_e(domain)}/">{_e(domain.replace("_", " "))}</a>'
        for domain in source["domains"]
    )
    evidence_sections = []
    if metrics:
        evidence_sections.append(
            '<section class="cn-section"><div class="cn-section__head"><p class="cn-kicker">Pulse join</p><h2>Current retained metrics</h2>'
            '<p>These metrics join by exact source id or the explicitly typed release-family mapping.</p></div>'
            f'<div class="cn-table-wrap"><table><thead><tr><th>Metric</th><th>Value</th><th>State</th></tr></thead><tbody>{metric_rows}</tbody></table></div></section>'
        )
    if releases:
        evidence_sections.append(
            '<section class="cn-section"><div class="cn-section__head"><p class="cn-kicker">Release joins</p><h2>Related publication monitors</h2></div>'
            f'<ul class="cn-link-list">{release_items}</ul></section>'
        )
    if latest:
        evidence_sections.append(
            '<section class="cn-section"><div class="cn-section__head"><p class="cn-kicker">Bitemporal ledger</p><h2>Latest retained row by source slice</h2>'
            '<p>Period, release and collection clocks remain separate; each receipt retains its revision and checksums.</p></div>'
            '<p class="cn-table-cue" id="source-ledger-scroll">Scroll horizontally to inspect every clock and receipt.</p>'
            f'<div class="cn-table-wrap" role="region" tabindex="0" aria-label="Latest retained observations by source slice; horizontally scrollable" aria-describedby="source-ledger-scroll"><table><caption class="cn-visually-hidden">Latest retained observations by source slice</caption><thead><tr><th>Series and slice</th><th>Value</th><th>Period end</th><th>Released</th><th>Collected</th><th>Revision</th><th>Receipt</th></tr></thead><tbody>{observation_rows}</tbody></table></div></section>'
        )
    if not evidence_sections:
        evidence_sections.append(
            '<section class="cn-section cn-empty"><h2>No retained public observations</h2>'
            '<p>This source remains in the ledger so the gap is inspectable. No value has been inferred or substituted.</p></section>'
        )

    body = f'''
{_breadcrumbs((("China Observatory", "/china/"), ("Source ledger", "/china/sources/"), (source["name"], f'/china/sources/{source["source_id"]}/')))}
<header class="cn-pagehead cn-pagehead--detail"><p class="cn-kicker">Source / {_e(source["source_id"])}</p><h1>{_e(source["name"])}</h1>
<p>{_e(source["publisher"])}</p>{_status_badge(source["implementation"])}</header>
<section class="cn-facts" aria-label="Source facts">
<dl><div><dt>Access</dt><dd>{_e(_status_label(source["access_mode"]))}</dd></div><div><dt>Cadence</dt><dd>{_e(source["cadence"])}</dd></div>
<div><dt>Independence group</dt><dd class="cn-mono">{_e(source["independence_group"])}</dd></div><div><dt>Vintage support</dt><dd>{'yes' if source['vintage_support'] else 'no'}</dd></div>
<div><dt>Collector</dt><dd class="cn-mono">{_e(source["collector"])}</dd></div><div><dt>Retained rows</dt><dd>{source["observation_count"]}</dd></div></dl>
<div class="cn-chipset" aria-label="Economic domains">{domain_links}</div></section>
<section class="cn-section cn-source-note"><div class="cn-section__head"><p class="cn-kicker">Rights & method boundary</p><h2>Permitted use</h2></div><p>{_e(source["license_note"])}</p>
<p><a href="{_e(source["home_url"])}" rel="noopener">Publisher home ↗</a> · <a href="{_e(source["evidence_url"])}" rel="noopener">Registry evidence ↗</a></p>
<p><b>Dimensions named by the source plan:</b> {_e(", ".join(source["dimensions"]))}</p></section>
{''.join(evidence_sections)}
'''
    return _page(
        title=source["name"],
        description=f"Palimpsest source record for {source['name']}: access, implementation, evidence, rights and retained observations.",
        route=f'/china/sources/{source["source_id"]}/',
        body=body,
        index=index,
        page_type="WebPage",
    )


def _releases_index(index: Mapping[str, Any]) -> bytes:
    rows = []
    statuses = sorted({str(value.get("freshness", {}).get("status", "unknown")) for value in index["releases"]})
    for release in index["releases"]:
        freshness = str(release.get("freshness", {}).get("status", "unknown"))
        search = " ".join(
            [release["label"], release["metric_id"], release["source_id"], str(release["registry_source_id"] or "unregistered")]
        )
        rows.append(
            f'<li class="cn-record" data-cn-record data-cn-status="{_e(freshness)}" data-cn-text="{_e(search.lower())}">'
            f'<a class="cn-record__main" href="/china/releases/{_e(release["metric_id"])}/"><span class="cn-record__id">{_e(release["watch_id"])}</span>'
            f'<b>{_e(release["label"])}</b><span>latest visible: {_e(release.get("latest_publication_date") or "not available")}</span></a>'
            f'<div class="cn-record__state">{_status_badge(freshness)}<span class="cn-num">{_e(_fmt_value(release.get("value")))} {_e(release.get("unit", ""))}</span></div>'
            f'<p>{_e(_status_label(release["registry_relationship"]))} → {_e(release["registry_source_id"] or "no registry entry")}</p></li>'
        )
    body = f'''
{_breadcrumbs((("China Observatory", "/china/"), ("Release docket", "/china/releases/")))}
<header class="cn-pagehead"><p class="cn-kicker">Release docket / {index["counts"]["release_monitors"]} watches</p><h1>Publication clocks, not economic predictions</h1>
<p>Every watch preserves what was visible, when it was collected and whether its registry relationship is exact or only a publisher-family aid.</p></header>
{_controls(statuses=statuses, noun="release watches")}
<ul class="cn-records" data-cn-list>{''.join(rows)}</ul>
<aside class="cn-limit"><h2>Clock precision</h2><p>{_e(index['limitations'][-1])}</p></aside>
'''
    return _page(
        title="China release docket",
        description="Seven monitored China publication clocks with freshness, provenance and explicit source-family relationships.",
        route="/china/releases/",
        body=body,
        index=index,
    )


def _release_detail(release: Mapping[str, Any], index: Mapping[str, Any]) -> bytes:
    source_by_id = {source["source_id"]: source for source in index["sources"]}
    registry_source_id = release["registry_source_id"]
    source = source_by_id.get(registry_source_id) if registry_source_id is not None else None
    freshness = release.get("freshness", {})
    revision = release.get("revision", {})
    comparison = release.get("comparability", {})
    evidence = release.get("evidence", {})
    registry_family = (
        f'<a href="/china/sources/{_e(source["source_id"])}/">{_e(source["name"])}</a>'
        if source is not None
        else '<span>no matching registry entry</span>'
    )
    body = f'''
{_breadcrumbs((("China Observatory", "/china/"), ("Release docket", "/china/releases/"), (release["label"], f'/china/releases/{release["metric_id"]}/')))}
<header class="cn-pagehead cn-pagehead--detail"><p class="cn-kicker">Release monitor / {_e(release["watch_id"])}</p><h1>{_e(release["label"])}</h1>
<p>{_e(comparison.get("concept", "Publication age"))}</p>{_status_badge(str(freshness.get("status", release.get("status", "unknown"))))}</header>
<section class="cn-release-read" aria-label="Release age reading"><div><span>visible age</span><strong class="cn-num">{_e(_fmt_value(release.get("value")))}</strong><small>{_e(release.get("unit", ""))}</small></div>
<p>Latest visible publication: <b>{_e(release.get("latest_publication_date") or "not available")}</b><br>Latest reported period: <b>{_e(release.get("latest_period") or "not available")}</b></p></section>
<section class="cn-facts"><dl>
<div><dt>Release source id</dt><dd class="cn-mono">{_e(release["source_id"])}</dd></div><div><dt>Registry family</dt><dd>{registry_family}</dd></div>
<div><dt>Relationship</dt><dd>{_e(_status_label(release["registry_relationship"]))}</dd></div><div><dt>Independent group</dt><dd class="cn-mono">{_e(release["independence_group"])}</dd></div>
<div><dt>Basis</dt><dd>{_e(release.get("basis", "not available"))}</dd></div><div><dt>Nominal interval</dt><dd>{_e(release.get("nominal_interval_days", "—"))} days</dd></div>
<div><dt>Collected at</dt><dd class="cn-mono">{_e(release.get("collected_at", "not available"))}</dd></div><div><dt>Revision state</dt><dd>{_e(_status_label(str(revision.get("status", "not available"))))}</dd></div>
</dl></section>
<aside class="cn-relationship"><p class="cn-kicker">Join semantics</p><h2>{_e(_status_label(release["registry_relationship"]))}</h2><p>{_e(release["registry_relationship_note"])}</p></aside>
<section class="cn-section"><div class="cn-section__head"><p class="cn-kicker">Receipt</p><h2>Retained evidence pointer</h2></div>
<dl class="cn-receipt"><div><dt>Evidence URL</dt><dd><a href="{_e(evidence.get("url", "#"))}">{_e(evidence.get("url", "not available"))}</a></dd></div>
<div><dt>Evidence SHA-256</dt><dd class="cn-mono">{_e(evidence.get("sha256", "not available"))}</dd></div>
<div><dt>Comparability basis</dt><dd>{_e(comparison.get("basis", "not available"))}</dd></div></dl>
<p class="cn-caveat">{_e(release.get("limitation", "No additional limitation recorded."))}</p></section>
'''
    return _page(
        title=release["label"],
        description=f"Publication-age monitor for {release['label']}, including clocks, evidence and registry relationship.",
        route=f'/china/releases/{release["metric_id"]}/',
        body=body,
        index=index,
        page_type="Dataset",
    )


def _domains_index(index: Mapping[str, Any]) -> bytes:
    rows = []
    statuses = sorted({domain["status"] for domain in index["domains"]})
    for domain in index["domains"]:
        search = " ".join(
            [domain["label"], domain["description"], *domain["source_ids"], *domain["observed_groups"]]
        )
        rows.append(
            f'<li class="cn-record cn-record--domain" data-cn-record data-cn-status="{_e(domain["status"])}" data-cn-text="{_e(search.lower())}">'
            f'<a class="cn-record__main" href="/china/domains/{_e(domain["domain"])}/"><span class="cn-record__id">{_e(domain["domain"])}</span>'
            f'<b>{_e(domain["label"])}</b><span>{_e(domain["description"])}</span></a>'
            f'<div class="cn-record__state">{_status_badge(domain["status"])}<span>{len(domain["source_ids"])} source families</span></div>'
            f'<p>{len(domain["observed_groups"])} observed groups · {len(domain["adapter_ready_groups"])} adapter-ready groups</p></li>'
        )
    body = f'''
{_breadcrumbs((("China Observatory", "/china/"), ("Coverage domains", "/china/domains/")))}
<header class="cn-pagehead"><p class="cn-kicker">Coverage matrix / {index["counts"]["domains"]} domains</p><h1>Where the loom holds—and where it opens</h1>
<p>Observed groups come from the pulse. Registered source families come from the source ledger. The two are intentionally not collapsed.</p></header>
{_controls(statuses=statuses, noun="domains")}
<ul class="cn-records" data-cn-list>{''.join(rows)}</ul>
'''
    return _page(
        title="China economic coverage domains",
        description="Twelve China economic domains showing observed groups, adapter-ready routes and registered source coverage.",
        route="/china/domains/",
        body=body,
        index=index,
    )


def _domain_detail(domain: Mapping[str, Any], index: Mapping[str, Any]) -> bytes:
    source_by_id = {source["source_id"]: source for source in index["sources"]}
    metric_by_id = {
        metric["metric_id"]: metric
        for desk in index["desks"]
        for metric in desk["metrics"]
    }
    source_rows = []
    for source_id in domain["source_ids"]:
        source = source_by_id[source_id]
        source_rows.append(
            '<tr>'
            f'<th scope="row"><a href="/china/sources/{_e(source_id)}/">{_e(source["name"])}</a></th>'
            f'<td>{_status_badge(source["implementation"])}</td><td>{_e(source["cadence"])}</td>'
            f'<td class="cn-mono">{_e(source["independence_group"])}</td>'
            '</tr>'
        )
    metric_rows = []
    for metric_id in domain["pulse_metric_ids"]:
        metric = metric_by_id[metric_id]
        metric_rows.append(
            '<tr>'
            f'<th scope="row">{_e(metric["label"])}</th><td class="cn-num">{_e(_fmt_value(metric.get("value")))} {_e(metric.get("unit", ""))}</td>'
            f'<td>{_status_badge(str(metric.get("status", "unknown")))}</td><td class="cn-mono">{_e(metric.get("source_id", "—"))}</td>'
            '</tr>'
        )
    observed = "".join(f'<li class="cn-group cn-group--observed">{_e(value)}</li>' for value in domain["observed_groups"])
    ready = "".join(f'<li class="cn-group cn-group--ready">{_e(value)}</li>' for value in domain["adapter_ready_groups"])
    metrics_section = (
        '<section class="cn-section"><div class="cn-section__head"><p class="cn-kicker">Pulse join</p><h2>Metrics linked to registered families</h2>'
        '<p>A release-family mapping may create a discovery link; it does not change the registry implementation state.</p></div>'
        f'<div class="cn-table-wrap"><table><thead><tr><th>Metric</th><th>Value</th><th>State</th><th>Pulse source</th></tr></thead><tbody>{"".join(metric_rows)}</tbody></table></div></section>'
        if metric_rows
        else '<section class="cn-section cn-empty"><h2>No joined pulse metrics</h2><p>The domain remains visible because registered and adapter-ready coverage are evidence too. No metric has been inferred.</p></section>'
    )
    body = f'''
{_breadcrumbs((("China Observatory", "/china/"), ("Coverage domains", "/china/domains/"), (domain["label"], f'/china/domains/{domain["domain"]}/')))}
<header class="cn-pagehead cn-pagehead--detail"><p class="cn-kicker">Domain / {_e(domain["domain"])}</p><h1>{_e(domain["label"])}</h1>
<p>{_e(domain["description"])}</p>{_status_badge(domain["status"])}</header>
<section class="cn-domain-state"><div><p class="cn-kicker">Observed groups</p><ul>{observed or '<li class="cn-group cn-group--gap">none retained</li>'}</ul></div>
<div><p class="cn-kicker">Adapter-ready groups</p><ul>{ready or '<li class="cn-group cn-group--gap">none registered</li>'}</ul></div></section>
<section class="cn-section"><div class="cn-section__head"><p class="cn-kicker">Source ledger join</p><h2>{len(source_rows)} registered source families</h2></div>
<div class="cn-table-wrap"><table><thead><tr><th>Source</th><th>Implementation</th><th>Cadence</th><th>Independent group</th></tr></thead><tbody>{''.join(source_rows)}</tbody></table></div></section>
{metrics_section}
'''
    return _page(
        title=f'{domain["label"]} — China coverage',
        description=domain["description"],
        route=f'/china/domains/{domain["domain"]}/',
        body=body,
        index=index,
    )


def _sitemap(html_paths: Sequence[Path], index: Mapping[str, Any]) -> bytes:
    modified = str(index["head"]["generated_at"])[:10]
    urls = []
    for path in sorted(html_paths, key=str):
        relative = path.relative_to(ROOT)
        route = "/" + str(relative).replace(os.sep, "/")
        if route.endswith("index.html"):
            route = route[: -len("index.html")]
        urls.append(
            f"  <url><loc>{_e('https://palimpsest.info' + route)}</loc><lastmod>{_e(modified)}</lastmod></url>"
        )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- GENERATED BY scripts/build_china_site.py -->\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(urls)
        + "\n</urlset>\n"
    ).encode("utf-8")


def build_outputs(*, root: Path = ROOT) -> dict[Path, bytes]:
    index = build_index(root=root)
    outputs: dict[Path, bytes] = {
        root / "readings" / "china-index-latest.json": canonical_json(index),
        root / "china" / "index.html": _home(index),
        root / "china" / "sources" / "index.html": _sources_index(index),
        root / "china" / "releases" / "index.html": _releases_index(index),
        root / "china" / "domains" / "index.html": _domains_index(index),
    }
    for source in index["sources"]:
        outputs[root / "china" / "sources" / source["source_id"] / "index.html"] = _source_detail(source, index)
    for release in index["releases"]:
        outputs[root / "china" / "releases" / release["metric_id"] / "index.html"] = _release_detail(release, index)
    for domain in index["domains"]:
        outputs[root / "china" / "domains" / domain["domain"] / "index.html"] = _domain_detail(domain, index)

    html_paths = [path for path in outputs if path.suffix == ".html"]
    sitemap_path = root / "china" / "sitemap.xml"
    outputs[sitemap_path] = _sitemap(html_paths, index)
    manifest_path = root / "china" / "generated-manifest.json"
    manifest_outputs = sorted(
        str(path.relative_to(root)).replace(os.sep, "/")
        for path in [*outputs, manifest_path]
    )
    output_sha256 = {
        str(path.relative_to(root)).replace(os.sep, "/"): _sha256(payload)
        for path, payload in sorted(outputs.items(), key=lambda item: str(item[0]))
    }
    outputs[manifest_path] = canonical_json(
        {
            "schema_version": MANIFEST_SCHEMA,
            "generated_at": index["head"]["generated_at"],
            "generator": "scripts/build_china_site.py",
            "outputs": manifest_outputs,
            "output_sha256": output_sha256,
        }
    )
    return outputs


def _atomic_write(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fchmod(handle.fileno(), 0o644)
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        directory_fd = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _managed_extras(outputs: Mapping[Path, bytes], *, root: Path) -> list[Path]:
    expected = set(outputs)
    extras: list[Path] = []
    for collection in ("sources", "releases", "domains"):
        collection_root = root / "china" / collection
        if not collection_root.exists():
            continue
        for candidate in collection_root.glob("*/index.html"):
            if candidate in expected:
                continue
            try:
                prefix = candidate.read_bytes()[:4096]
            except OSError as exc:
                raise ChinaSiteError(f"cannot inspect managed candidate {candidate}: {exc}") from exc
            if GENERATED_MARKER.encode() in prefix:
                extras.append(candidate)
    return sorted(extras)


def check(outputs: Mapping[Path, bytes], *, root: Path = ROOT) -> list[str]:
    drift: list[str] = []
    for path, expected in sorted(outputs.items(), key=lambda item: str(item[0])):
        try:
            current = path.read_bytes()
        except FileNotFoundError:
            drift.append(f"missing {path.relative_to(root)}")
            continue
        if current != expected:
            drift.append(f"stale {path.relative_to(root)}")
    for path in _managed_extras(outputs, root=root):
        drift.append(f"extra {path.relative_to(root)}")
    return drift


def publish(outputs: Mapping[Path, bytes], *, root: Path = ROOT) -> tuple[int, int, int]:
    changed = 0
    unchanged = 0
    manifest_path = root / "china" / "generated-manifest.json"
    if manifest_path not in outputs:
        raise ChinaSiteError("generated output set is missing the publication manifest")

    # The manifest is the commit marker for this multi-file static publication.
    # Write all content, retire only marker-owned stale details, then replace the
    # manifest last so consumers never see a manifest for a partial build.
    content_outputs = [
        item for item in sorted(outputs.items(), key=lambda item: str(item[0]))
        if item[0] != manifest_path
    ]
    for path, payload in content_outputs:
        try:
            current = path.read_bytes()
        except FileNotFoundError:
            current = None
        if current == payload:
            unchanged += 1
            continue
        _atomic_write(path, payload)
        changed += 1
    removed = 0
    for extra in _managed_extras(outputs, root=root):
        extra.unlink()
        removed += 1
        try:
            extra.parent.rmdir()
        except OSError:
            pass

    manifest_payload = outputs[manifest_path]
    try:
        current_manifest = manifest_path.read_bytes()
    except FileNotFoundError:
        current_manifest = None
    if current_manifest == manifest_payload:
        unchanged += 1
    else:
        _atomic_write(manifest_path, manifest_payload)
        changed += 1
    return changed, unchanged, removed


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    args = parser.parse_args(list(argv) if argv is not None else None)
    try:
        outputs = build_outputs()
        if args.check:
            drift = check(outputs)
            for item in drift:
                print(item)
            if drift:
                print(f"China Observatory drift: {len(drift)} file(s)")
                return 1
            print(f"China Observatory current: {len(outputs)} files")
            return 0
        changed, unchanged, removed = publish(outputs)
    except ChinaSiteError as exc:
        parser.error(str(exc))
    print(
        f"China Observatory -> china/ · {len(outputs)} files · "
        f"{changed} updated · {unchanged} unchanged · {removed} retired"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
