"""Circumvention-demand runner — pull Tor Metrics' CN series and publish the
demand-side censorship barometer.

History is keyed by DATA date. Tor Metrics serves arbitrary ranges, so the
first run seeds a deep record in one fetch (CIRCUMVENTION_BACKFILL_DAYS,
default 400) and cron runs top up a short window. Recent days are revised
upward by Tor as reports arrive, so the merge REPLACES a date's record when
the new read differs — the history is Tor's best current estimate per day,
and the fetch date of the last revision is recorded.
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timedelta, timezone

from collectors.circumvention_demand import collect, transport_shift

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
READINGS = os.path.join(ROOT, "readings")
OUT = os.path.join(READINGS, "circumvention-demand-latest.json")
HIST = os.path.join(READINGS, "circumvention-demand-history.jsonl")

WINDOW_DAYS = 30


def _load_history() -> dict[str, dict]:
    rows: dict[str, dict] = {}
    if os.path.exists(HIST):
        with open(HIST, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if rec.get("date"):
                    rows[rec["date"]] = rec
    return rows


def main() -> None:
    now = datetime.now(timezone.utc)
    history = _load_history()
    back = int(os.environ.get("CIRCUMVENTION_BACKFILL_DAYS", "0")) or \
        (WINDOW_DAYS if history else 400)
    start = (now - timedelta(days=back)).strftime("%Y-%m-%d")
    end = now.strftime("%Y-%m-%d")

    fresh = collect(start, end)

    # Honesty guard: all three tables failed -> abstain, publish nothing.
    if not fresh:
        print("tor metrics returned nothing parseable — abstaining")
        return

    changed = 0
    for date, row in fresh.items():
        prior = history.get(date)
        merged = {**(prior or {}), **row}
        if merged != prior:
            merged["revised_at"] = end
            history[date] = merged
            changed += 1

    if changed:
        with open(HIST, "w", encoding="utf-8") as f:
            for date in sorted(history):
                f.write(json.dumps(history[date], ensure_ascii=False,
                                   sort_keys=True) + "\n")

    last = max(d for d, r in history.items() if r.get("bridge_users") is not None)
    shifts = transport_shift(history)
    latest = {
        "generated_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source": ("Tor Metrics (CC0) userstats — bridge users, relay users, "
                   "and per-transport bridge estimates for country=cn"),
        "asof": last,
        "reading": {k: v for k, v in history[last].items() if k != "revised_at"},
        "transport_shifts": shifts,
        "history_days": len(history),
        "method_note": (
            "Bridge users = demand for unlisted entry points (the "
            "demand-to-circumvent series). Relay users = direct reachability, "
            "structurally near-floor behind the GFW. A transport halving while "
            "another surges (transport_shifts) is the public fingerprint of a "
            "new GFW classifier deployment. Estimates are Tor's, from sampled "
            "directory requests; transport rows keep Tor's low/high bounds. "
            "No probe traffic is generated by this collector."
        ),
    }
    os.makedirs(READINGS, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(latest, f, ensure_ascii=False, indent=1, sort_keys=True)

    print(f"circumvention-demand: asof {last}, {changed} dates added/revised, "
          f"{len(history)} days accrued, {len(shifts)} transport shifts")


if __name__ == "__main__":
    main()
